name: test
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test_the_github_actions
        run: |
          echo "Build is ${{ vars.START }}"
          echo "Build is ${{ vars.COMPLETE }}"
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test_the_github_actions
        run: |
          echo "test is started"
          echo "test is completed"
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: test_the_github_actions
        run: |
          echo "deploy is started"
          echo "deploy is completed"
